include: package:flutter_lints/flutter.yaml

# Dart 3.7 Formatter Ayarları
formatter:
  page_width: 100

linter:
  # Dart 3.7 "The rules below are enabled by default
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - file_names
    - hash_and_equals
    # iterable_contains_unrelated_type - Dart 3.3'te kaldırıldı
    # list_remove_unrelated_type - Dart 3.3'te kaldırıldı
    - no_duplicate_case_values
    - non_constant_identifier_names
    - package_prefixed_library_names
    - prefer_generic_function_type_aliases
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - type_init_formals
    - unnecessary_overrides
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Dart 3.7 "Additional rules worth enabling"
    - always_declare_return_types
    - annotate_overrides
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    # avoid_returning_null_for_future - Dart 3.3'te kaldırıldı
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - comment_references
    - deprecated_consistency
    - directives_ordering
    - implicit_call_tearoffs
    - join_return_with_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - prefer_spread_collections
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_this
    - use_named_constants
    - unnecessary_underscores # Dart 3.7 wildcard variables için desteği belirtir
