name: zenvivatodo
description: Sağlıklı ve Düzenli Bir Yaşam için To-Do Uygulaması

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Dart 3.7 ile uyumlu olması için güncellendi

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.5
  
  # State management
  provider: ^6.1.1
  
  # Shared preferences for theme and user session
  shared_preferences: ^2.2.0
  
  # Date and time formatting
  intl: ^0.19.0  # flutter_localizations için gerekli sürüm
  
  # Timer for reminders
  rxdart: ^0.28.0
  timezone: ^0.10.0
  
  # Notifications
  flutter_local_notifications: ^19.0.0
  
  # Security
  crypto: ^3.0.3
  
  # API ve Network
  dio: ^5.8.0+1                       # API istekleri için
  json_annotation: ^4.9.0           # JSON serialization için
  connectivity_plus: ^6.1.3         # İnternet bağlantı durumu için
  
  # Geliştirilen State management
  # flutter_riverpod: ^2.4.9        # (Opsiyonel, provider yerine kullanılabilir)
  
  # Diğer bağımlılıklar
  collection: ^1.17.2
  uuid: ^4.5.1
  flutter_animate: ^4.2.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.3.0         # Uygulama versiyon bilgisi için
  url_launcher: ^6.2.4              # URL açmak için
  
  # Web için JS interoperabilite
  web: ^1.1.1
  flutter_riverpod: ^2.6.1
  get: ^4.6.6
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.0         # JSON serialization için
  build_runner: ^2.4.8              # Code generation için

flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

# Dart formatter ayarları
analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
