name: zenvivatodo
description: Sağlıklı ve Düzenli Bir Yaşam için To-Do Uygulaması

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Dart 3.7 ile uyumlu olması için güncellendi

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  
  # Database
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.2.2
  
  # State management
  provider: ^6.1.1
  
  # Shared preferences for theme and user session
  shared_preferences: ^2.2.2
  
  # Date and time formatting
  intl: ^0.19.0
  
  # Timer for reminders
  rxdart: ^0.27.7
  timezone: ^0.9.2
  
  # Notifications - Yeniden etkinleştirildi ve güncellendi
  flutter_local_notifications: ^16.1.0
  
  # Security
  crypto: ^3.0.3
  
  # Yeni eklenen bağımlılıklar
  collection: ^1.18.0    # Dart koleksiyon yardımcıları için
  uuid: ^4.2.1          # Benzersiz ID oluşturmak için
  flutter_animate: ^4.4.0  # Animasyonlar için
  google_fonts: ^6.1.0  # Modern font desteği
  
  # Web için JS interoperabilite (dart:html yerine)
  web: ^0.5.0           # Web destekli API'ler için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

# Dart formatter ayarları - Dart 3.7 yeni biçimlendirme stili
formatter:
  page_width: 100  # Sayfa genişliği
